#!/usr/bin/env python

import sys
import math

def complain():
    print("Error: Please provide a number to be checked.")

def main():
    if (len(sys.argv) < 2):
        complain()
        return -1

    if not sys.argv[1].isdigit():
        complain()
        return -1

    number = int(sys.argv[1]);
    isPrime = True

    if (number % 2 == 0 and number > 2):
        print("2 divides %d evenly. NOT PRIME." % (number,))
        isPrime = False
    for i in range(3, int(math.sqrt(number)) + 1, 2):
        if number % i == 0:
            print("%d divides %d evenly. NOT PRIME." % (i, number,))
            isPrime = False

    if (isPrime):
        print("%d is A PRIME NUMBER." % (number,))

    return 0


if __name__ == "__main__":
    main()
